name: Build Android WebView APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install \
            "cmdline-tools;latest" \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "build-tools;30.0.3"

      # === Siapkan project: unzip kalau repo berisi ZIP, lalu cari folder yang ada settings.gradle ===
      - name: Prepare project (unzip & detect project dir)
        shell: bash
        run: |
          set -e
          echo "Root listing:"
          ls -la

          if ls *.zip >/dev/null 2>&1; then
            Z="$(ls *.zip | head -n1)"
            echo "Found zip: $Z -> unzip..."
            unzip -o "$Z" -d .
          fi

          if [ -f settings.gradle ] || [ -f settings.gradle.kts ]; then
            PROJECT_DIR="."
          else
            CANDIDATE="$(find . -maxdepth 2 -type f \( -name 'settings.gradle' -o -name 'settings.gradle.kts' \) | head -n1)"
            [ -z "$CANDIDATE" ] && { echo "::error::settings.gradle tidak ditemukan. Pastikan kamu upload isi project Android (bukan ZIP kosong)."; exit 1; }
            PROJECT_DIR="$(dirname "$CANDIDATE")"
          fi

          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
          echo "Detected PROJECT_DIR=$PROJECT_DIR"
          ls -la "$PROJECT_DIR"

      # === Buat Gradle Wrapper (biar build stabil) ===
      - name: Generate Gradle Wrapper (7.6.1)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.6.1
          build-root-directory: ${{ env.PROJECT_DIR }}
          arguments: >
            wrapper
            --gradle-version 7.6.1

      # === Build pakai wrapper + log lengkap ke file ===
      - name: Build debug APK with wrapper (verbose)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          chmod +x ./gradlew
          ./gradlew --version
          ./gradlew --warning-mode all --stacktrace --info assembleDebug | tee build-logs.txt

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: POTOTIME-Android-Debug-APK
          path: |
            ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/app-debug.apk
            ${{ env.PROJECT_DIR }}/build-logs.txt
